name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Swift on ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: swift-actions/setup-swift@v2
    - uses: actions/checkout@v2
    - name: Build
      run: swift build
